# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Course.destroy_all
wdi = Course.create(name: "Web Development Immersive", img: "https://misk.org.sa/miskacademy/wp-content/uploads/sites/5/2018/09/p-6.png", short_description: "Full-time course for career changers", long_description: "In this 12-week course, students become junior-level web developers by building rails applications, developing their own ideas into functional web applications, creating a portfolio of their work, and embarking on the career path of a web developer. This course will give aspiring Ruby on Rails developers the confidence to build projects from start to finish at a professional level. The focus of this course is learning to program in Ruby and creating Rails web applications. However, WDI as a whole focuses on teaching students how to be professional full-stack web developers capable of building a scalable product with a team of developers. Therefore, in addition to teaching Rails, this course also includes lessons on computer science, JavaScript, command line basics, Git, GitHub, and database schemas.", duration: "12 Weeks", program_id: "??")
ds = Course.create(name: "Data Science Immersive", img: "https://misk.org.sa/miskacademy/wp-content/uploads/sites/5/2018/05/p-2.png", short_description: "Full-time course for career changers", long_description: "In this 12-week, full-time course students analyze massive data sets, and predict what happens next through predictive modeling and pattern recognition. Students create a polished portfolio of work that showcases their ability to create machine-learned insights in a way that is impactful to key stakeholders.", duration: "12 Weeks", program_id: "??")
ux = Course.create(name: "User Experience Design Immersive", img: "https://misk.org.sa/miskacademy/wp-content/uploads/sites/5/2018/05/p-2.png", short_description: "Full-time course for career changers", long_description: "A User Experience Designer is able to think outside the realm of what’s “possible” in order to create experiences that address the needs of customers in a way that brings them joy and delight. This requires a great deal of empathy, imagination, and skill", duration: "10 Weeks", program_id: "??")
